### ISSUE TITLE
no attribute create_environment on ebs

### ISSUE THREAD

**Issue by colbygk** [hsingh/ansible-elastic-beanstalk#14]
When attempting to use elasticbeanstalk_env, I am getting:

`'NoneType' object has no attribute 'create_environment'`

I see in `library/elasticbeanstalk_env.py` the reference but am not sure where the ebs obj is coming from and why/why not it would not have that method associated with it.

I'm currently using this with ansible 2.2.0

**Comment by colbygk** [comment]
This appears to be an issue of using boto and what it returns as its ebs handle. I am currently using boto 2.40.0

**Comment by hsingh** [comment]
Please verify if this is still an issue in the new 2.0 version
