### ISSUE TITLE
Question for creating apps in a vpc

### ISSUE THREAD

**Issue by ghost** [hsingh/ansible-elastic-beanstalk#17]
Hi there,

I have been searching for an answer how to assign an application inside of a vpc but the documentation from Amazon is not helping. I was trying to use 

```
         - Namespace: aws:ec2:vpc
           OptionName: VPCId
           Value: vpc-name
```

But it returns the error: 

```
failed: [localhost] => {"failed": true}
msg: Configuration validation exception: You cannot migrate an environment to a VPC. Launch a new environment in the VPC.
```

Also, would you happen to know the proper NameSpace values to launch the ELB with an RDS database? The Amazon documentation is very confusing and I have not been able to find a satisfactory way of doing this as this guide doesn't work for me https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/vpc-rds.html . It would seem to be that the minimum values are:

```
         - Namespace: aws:ec2:vpc
           OptionName: VPCId
           Value: vpc-name
         - Namespace: aws:ec2:vpc
           OptionName: Subnets
           Value: subnet-1
         - Namespace: aws:ec2:vpc
           OptionName: ELBSubnets
           Value: subnet-2
         - Namespace: aws:ec2:vpc
           OptionName: DBSubnets
           Value: subnet-3,subnet-4
```

**Comment by fvant** [comment]
Your vpc snippet is correct (you use the real vpcid, right)  but unfortunately you can not migrate an already existing env that was outside a VPC to a VPC. You need to terminate the running env  and then your play will create it in the vpc
