### ISSUE TITLE
updating env fails if existing env has no versionlabel

### ISSUE THREAD

**Issue by nergdron** [hsingh/ansible-elastic-beanstalk#26]
If I've deployed an application with no version, then trying to update that application later fails on https://github.com/hsingh/ansible-elastic-beanstalk/blob/master/library/elasticbeanstalk_env.py#L218:

```
    "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_WPlmQ2/ansible_module_elasticbeanstalk_env.py\", line 410, in <module>\n    main()\n  File \"/tmp/ansible_WPlmQ2/ansible_module_elasticbeanstalk_env.py\", line 374, in main\n    updates = update_required(ebs, env, module.params)\n  File \"/tmp/ansible_WPlmQ2/ansible_module_elasticbeanstalk_env.py\", line 218, in update_required\n    if params[\"version_label\"] and env[\"VersionLabel\"] != params[\"version_label\"]:\nKeyError: 'VersionLabel'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE"
}
```

Fix would be to check if key is set before using env["VersionLabel"].

**Comment by JefStat** [comment]
Root problem I've noticed is that `describe_env` is returning `None` in my particular case the call to `ebs.describe_environments` is not returning any environments. I've yet to figure out why though.

**Comment by JefStat** [comment]
Found our issue was that Region had to be specified ansible was using a default region that was incorrect for our beanstalk deployment
