### ISSUE TITLE
you should submit this module to be added to ansible core

### ISSUE THREAD

**Issue by aoyawale** [hsingh/ansible-elastic-beanstalk#35]
I see this being used by most folks out there much like the ec2 modules are used.

**Comment by viper233** [comment]
I'd like to get this pushed upstream too, with @radeinla configuration template. @hsingh are you still interested in maintaining this?

**Comment by viper233** [comment]
I've gone ahead and submitted a PR for this, hope that's ok. I've included the other PR for the elasticbeanstalk_app too.

**Comment by sidewinder12s** [comment]
@viper233 That got killed on review 😄 

Did you push elasticbeanstalk_env?

**Comment by viper233** [comment]
haha! I got some _great feedback_ is what you meant right? :P I was planning on submitting PRs for the other modules when this PR approved.. or almost approved. I'm a python noob so looking for the feedback and experience. It's been pretty positive for me so far.

**Comment by viper233** [comment]
https://github.com/ansible/ansible/pull/31079 PR was merged!!!! @sidewinder12s I'll start work on the other modules and fact modules tonight!

**Comment by sidewinder12s** [comment]
Too bad I don't use EB that much anymore, but good to see it get merged in!

**Comment by aoyawale** [comment]
That is awesome! I heard some folks wanting to use this so its great it got merged :)

Jonathan Lozada De La Matta

Sent with [ProtonMail](https://protonmail.com) Secure Email.

-------- Original Message --------
