### ISSUE TITLE
resource name

### ISSUE THREAD

**Issue by driller23** [hsingh/ansible-elastic-beanstalk#9]
Hi,

im trying to add the ability of resource name on needed namespace such as the autoscaling trigger.

do you know if the current module can handle that? how?
is boto 2 which is used here has the ability for that?

Igal

**Comment by hsingh** [comment]
I don't understand the issue, can you please clarify

**Comment by fvant** [comment]
See these docs for the options and their namespaces

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options.html   

http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/command-options-general.html
